# 1. 建议server.port 参数通过main方法参数传入 "--server.port=xxx"
# 2. 由于启动顺序的问题 ,需要将连接config server相关配置放于 bootstrap.yml 中
#

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  http:
    multipart:
      max-file-size: 200Mb        #默认1M
      max-request-size: 250Mb     # 默认10M
  zipkin:
    base-url: http://127.0.0.1:7904/
  sleuth:
    sampler:
      percentage: 1.0 #采样率  0-1.0  -->  0%-100%
  cloud:
    stream:
      bindings:
        input:
          destination: finance


logging:
  level:
    feign: debug
    com.yokimi.ebusiness_cloud.feign.AccountFeignClient: debug
endpoints:
  actuator:
    enabled:  true


